export const EPUB_EXT = '.epub'
export const ZIP_EXT = '.zip'
export const MIMETYPE_FILE = 'mimetype'
export const METAINF_FOLDER = 'META-INF'
export const CONTAINER_XML = 'container.xml'
export const WYSEBEE_OPF = 'wysebee.opf'
